--
-- Recreate the Rhapsody schema.
--
CREATE TABLE DB_INFO ( DB_VERSION INTEGER );

CREATE TABLE TRACK ( TRACK_ID INTEGER PRIMARY KEY, TRACK_TYPE INTEGER, IN_LIBRARY INTEGER, URI TEXT, DATE_ADDED TEXT, LAST_MODIFIED TEXT, LAST_PLAYED TEXT, PLAY_COUNT INTEGER, CODEC TEXT, BITRATE INTEGER, FILE_SIZE INTEGER, SAMPLE_RATE INTEGER, CHANNELS INTEGER, PEAK_RMS TEXT, ARTIST_NAME TEXT, ARTIST_ID INTEGER, ARTIST_DISPLAY_NAME TEXT, TRACK_ARTIST_DISPLAY_NAME TEXT, ARTIST_SORT_NAME TEXT, ALBUM_NAME TEXT, ALBUM_SORT_NAME TEXT, ALBUM_TYPE TEXT, ALBUM_ID INTEGER, TRACK_NAME TEXT, TRACK_SORT_NAME TEXT, RHAPSODY_ID INTEGER, COMPOSER_NAME TEXT, CONDUCTOR_NAME TEXT, ENSEMBLE_NAME TEXT, PERFORMER_NAME TEXT, TRACK_DURATION INTEGER , TRACK_NUMBER INTEGER, TOTAL_TRACKS INTEGER, DISC_NUMBER INTEGER, TOTAL_DISKS INTEGER, RECORDING_COPYRIGHT TEXT, ALBUM_ART_COPYRIGHT TEXT, RELEASE_DATE TEXT, PARENTAL_ADVISORY INTEGER, IS_COMPILATION INTEGER, IS_CLASSICAL INTEGER, ALBUM_ART_LARGE TEXT, ALBUM_ART_SMALL TEXT, ADDITIONAL_ART TEXT, ARTIST_ROOT_GENRE TEXT, ARTIST_PRIMARY_GENRE TEXT, COMMENTS TEXT, KEYWORDS TEXT, BPM TEXT, GAIN TEXT, EQ TEXT, PARENT_LABEL TEXT, SUB_LABEL TEXT, MOOD TEXT, TRACK_RIPPED TEXT,TRACK_ARTIST_NAME TEXT,TRACK_ARTIST_ID INTEGER,USER_EDITED INTEGER,RHAPSODY_RIGHTS INTEGER,GENRE_ID STRING,ITEM_STATE INTEGER,RHAPSODY_RIGHTS_UPDATE_STATE INTEGER NOT NULL DEFAULT 0,UNIQUE(TRACK_ID,RHAPSODY_ID));
CREATE INDEX RHAPSODY_INDEX ON TRACK(RHAPSODY_ID);
CREATE INDEX URI_INDEX ON TRACK(URI);
CREATE VIEW VIEW_TRACKS AS SELECT TRACK.* FROM TRACK WHERE ITEM_STATE!=2;

CREATE TABLE PLAYLIST ( PLAYLIST_ID INTEGER PRIMARY KEY, PLAYLIST_NAME TEXT, RHAPSODY_PLAYLIST_ID INTEGER, LAST_GUID_USED INTEGER, PLAYLIST_TYPE TEXT, SYNC_STATE INTEGER, AUTOPLAYLIST_USE_LOCAL INTEGER, AUTOPLAYLIST_USE_STREAM INTEGER, AUTOPLAYLIST_SORT_COLUMN INTEGER, AUTOPLAYLIST_SORT_ORDER TEXT, AUTOPLAYLIST_LENGTH_UNIT TEXT, AUTOPLAYLIST_LENGTH_VALUE INTEGER, AUTOPLAYLIST_ENABLE_CONDITIONS TEXT, AUTOPLAYLIST_CONDITION_LOGIC TEXT, AUTOPLAYLIST_V2_SERIALIZED TEXT, MIMETYPES TEXT,HASH TEXT);

CREATE TABLE DEVICE_STATION ( STATION_ID INTEGER PRIMARY KEY, STATION_RHAPID INTEGER, NAME TEXT, TYPE INTEGER, EXPIRATION TEXT, DEVICE_ID TEXT, PENDING_ACTION INTEGER );

CREATE TABLE DEVICE_PLAYLIST ( DEVICE_ID TEXT, DEVICE_TYPE INTEGER, PLAYLIST_ID INTEGER, PENDING_ACTION TEXT,  UNIQUE ( DEVICE_ID, DEVICE_TYPE, PLAYLIST_ID) );

CREATE TABLE PLAYLIST_TRACK ( PLAYLIST_ID INTEGER, TRACK_ID INTEGER, SEQUENCE INTEGER, GUID INTEGER );

CREATE TABLE AUTOPLAYLIST_RULE_TABLE ( PLAYLIST_ID INTEGER, COLUMN_NAME INTEGER, LOGIC_OPERATION TEXT, POSITIVE INTEGER, VALUE TEXT,VALUE2 TEXT );

CREATE TABLE STATION ( STATON_KEY INTEGER PRIMARY KEY, STATION_ID INTEGER, STATION_NAME TEXT, STATION_TYPE TEXT, IN_LIBRARY INTEGER, ARTISTS_IN_ROTATION TEXT, CREATOR TEXT, LIVE_URL TEXT );

CREATE TABLE UPNP_ARTIST ( UPNP_ARTIST_ID INTEGER PRIMARY KEY, UPNP_ARTIST_NAME TEXT );

CREATE TABLE UPNP_ALBUM_ARTIST ( UPNP_ALBUM_ARTIST_ID INTEGER PRIMARY KEY, UPNP_ALBUM_ARTIST_NAME TEXT );

CREATE TABLE PODCAST_CHANNEL (CHANNEL_ID INTEGER PRIMARY KEY,TITLE,XML_URL,XML_PATH,CATEGORY,COPYRIGHT,DESCRIPTION,DOCS,GENERATOR,LANGUAGE,LAST_BUILD_DATE,LINK,MANAGING_EDITOR,PUBDATE,RATING,SKIPDAYS,SKIPHOURS,TTL,WEBMASTER,STATUS );

CREATE TABLE PODCAST_ITEM (ITEM_ID INTEGER PRIMARY KEY,CHANNEL_ID,GUID,LOCAL_MEDIA_FILE_PATH,MEDIA_FILE_URL,MEDIA_FILE_TYPE,MEDIA_FILE_LENGTH,AUTHOR,CATEGORY,COMMENTS,DESCRIPTION,ITEM_INDEX,LINK,PUBDATE,TITLE );

CREATE TABLE CD ( LOCAL_CD_ID INTEGER PRIMARY KEY, CDDBID TEXT, CD_FOLDER_PATH TEXT, CD_LOCAL_EDIT_DATA TEXT, TRACK_ID INTEGER );

CREATE TABLE CD_TRACK ( LOCAL_CD_ID INTEGER, TRACK_ID INTEGER, SEQUENCE INTEGER );

CREATE TABLE RHAPSODY_FILE ( RHAPSODY_FILE_RHAPSODY_ID INTEGER, RHAPSODY_FILE_URI TEXT, IS_PURCHASED INTEGER, DRM INTEGER, HAS_LEAF_LICENSE INTEGER,TRACK_DRM_USER_GUID TEXT,TRACK_DRM_GUID TEXT);

CREATE TABLE RATINGS ( RATINGS_ID INTEGER PRIMARY KEY, RATINGS_LOCAL_TRACK_ID INTEGER, RATINGS_RHAPSODY_TRACK_ID INTEGER NOT NULL DEFAULT 0, RATINGS_VALUE INTEGER,RATINGS_NEED_SYNC_WITH_SERVER INTEGER,UNIQUE(RATINGS_LOCAL_TRACK_ID,RATINGS_RHAPSODY_TRACK_ID));

CREATE TABLE VIDEO ( VIDEO_ID INTEGER PRIMARY KEY, CLIP_NAME TEXT, CLIP_SORT_NAME TEXT, FORMAT TEXT, PARENTAL_ADVISORY INTEGER, IN_LIBRARY INTEGER, URI TEXT, DIMENSIONS TEXT, FILE_SIZE INTEGER, DURATION INTEGER, BIT_RATE INTEGER, PRIMARY_GENRE TEXT, RATING INTEGER, ARTISTS TEXT, ARTISTS_SORT_NAME TEXT, DIRECTOR TEXT, DIRECTOR_SORT_NAME TEXT, DATE_ADDED TEXT, LAST_PLAYED TEXT, COMMENTS TEXT, ARTIST_NAME TEXT, THUMB_NAIL BLOB  );

CREATE TABLE PHOTO ( PHOTO_ID INTEGER PRIMARY KEY, TITLE TEXT, ARTIST TEXT, ARTIST_SORT_NAME TEXT, FORMAT TEXT, SIZE INTEGER, LOCATION TEXT, RESOLUTION TEXT, DIMENSIONS TEXT, DATE_TAKEN TEXT, EQUIP_MAKE TEXT, EQUIP_MODEL TEXT, DATE_ADDED TEXT, DATE_MODIFIED TEXT, COMMENTS TEXT, IN_LIBRARY INTEGER, THUMB_NAIL BLOB, UNIQUE(LOCATION));

CREATE TABLE DEVICE_PHOTO( PHOTO_ID INTEGER, DEVICE_URI TEXT, DEVICE_ID  TEXT,UNIQUE(PHOTO_ID, DEVICE_URI) );

CREATE TABLE PHOTO_ALBUM ( ALBUM_ID INTEGER PRIMARY KEY, PHOTO_ALBUM_NAME TEXT,PHOTO_ALBUM_LOCATION TEXT, PHOTO_ALBUM_DATE_ADDED TEXT, PHOTO_ALBUM_THUMB_NAIL BLOB, UNIQUE(PHOTO_ALBUM_LOCATION));

CREATE TABLE PHOTO_ALBUM_CONTENT ( PHOTO_ALBUM_CONTENT_ALBUM_ID INTEGER, PHOTO_ALBUM_CONTENT_PHOTO_ID INTEGER, UNIQUE(PHOTO_ALBUM_CONTENT_ALBUM_ID,PHOTO_ALBUM_CONTENT_PHOTO_ID));

CREATE TABLE VIDEO_ALBUM ( ALBUM_ID INTEGER PRIMARY KEY, VIDEO_ALBUM_NAME TEXT,VIDEO_ALBUM_LOCATION TEXT, VIDEO_ALBUM_DATE_ADDED TEXT, VIDEO_ALBUM_THUMB_NAIL BLOB, UNIQUE(VIDEO_ALBUM_LOCATION));

CREATE TABLE VIDEO_ALBUM_CONTENT ( VIDEO_ALBUM_CONTENT_ALBUM_ID INTEGER, VIDEO_ALBUM_CONTENT_VIDEO_ID INTEGER, UNIQUE(VIDEO_ALBUM_CONTENT_ALBUM_ID,VIDEO_ALBUM_CONTENT_VIDEO_ID));
CREATE INDEX LOCAL_TRACK_ID_INDEX ON RATINGS(RATINGS_LOCAL_TRACK_ID);
CREATE INDEX RHAPSODY_TRACK_ID_INDEX ON RATINGS(RATINGS_RHAPSODY_TRACK_ID);
CREATE INDEX RATING_VALUE_INDEX ON RATINGS(RATINGS_VALUE);

CREATE TABLE MANAGED_TRACK ( MANAGED_TRACK_ID INTEGER PRIMARY KEY, RHAPSODY_ID INTEGER, ARTIST_ID INTEGER, ALBUM_ID INTEGER, TRACK_NAME TEXT, ARTIST_NAME TEXT, ALBUM_NAME TEXT, TRACK_DURATION INTEGER, FILE_SIZE INTEGER, CODEC TEXT, DATE_ADDED TEXT, URI TEXT, REFCOUNT INTEGER );

CREATE TABLE DOWNLOADSTATUS ( DOWNLOADSTATUS_RHAPID INTEGER PRIMARY KEY, DOWNLOADSTATUS_STATUS INTEGER );
