(defun test-pass-fail ()
  (interactive)
  (mark-whole-buffer)
  (shell-command-on-region (region-beginning) (region-end) "grep ^Rule" 1 1)
  (beginning-of-buffer)
  (while (looking-at "Rule")
    (join-line 1)
    (join-line 1)
    (next-line 1)
    (beginning-of-line))
  (mark-whole-buffer)
  (sort-lines nil (point-min) (point-max))
  (mark-whole-buffer)
  (shell-command-on-region (region-beginning) (region-end) "uniq -c" 1 1))

