

CPP=/sapmnt/appl_sw/gcc-4.7/bin/g++
CPPFLAGS=-g -std=c++11

all : 
	$(CPP) $(CPPFLAGS) -c counted.cpp
	$(CPP) $(CPPFLAGS) -c pointertest.cpp
	$(CPP) $(CPPFLAGS) -o pointertest pointertest.o counted.o



