
.PHONY : test

AC_TESTER    = ./ac_tester.sh

test :
	$(AC_TESTER) one_column_of_integers
	$(AC_TESTER) one_column_of_floats
	$(AC_TESTER) one_column_of_text
	$(AC_TESTER) one_column_of_flags
	$(AC_TESTER) three_columns
	$(AC_TESTER) multiple_date_formats

